# Dependabot configuration
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates#enabling-github-dependabot-version-updates
# https://til.simonwillison.net/github/dependabot-python-setup

# Dependabot est un outil GitHub qui surveille vos dépendances (bibliothèques, packages)
# et vous alerte ou génère automatiquement des mises à jour lorsque de nouvelles versions sont disponibles,
# notamment si elles corrigent des vulnérabilités.

version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly
    groups:
      python-packages:
        patterns:
          - "*"
